name: My First Passing Pipeline

on:
  push:
    branches: [ master ]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message to the logs
        run: echo "The pipeline executed perfectly!"
